name: test
on:
  push:
  pull_request:
jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4.1.0

      - name: Build and test this project
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=PROFILE $SRC_DIR
          make VERBOSE=1
          ./tree_test
          ./tree_test >> "$TEST_RES"

      - name: Analyze the result of GoogleTest with gcov
        run: |
          gcov build/CMakeFiles/tree_test.dir/source/avlTree.cc.gcno
          gcov build/CMakeFiles/tree_test.dir/source/bstTree.cc.gcno
          gcov build/CMakeFiles/tree_test.dir/source/gui.cc.gcno
          gcov build/CMakeFiles/tree_test.dir/source/main.cc.gcno

      - name: Install lcov and generate html file with lcov
        run: |
          sudo apt-get install lcov
          lcov --directory build/CMakeFiles/tree_test.dir/source --capture --output-file app.info
          lcov --remove app.info '*/usr/include/*' '*googletest*' 'Mock*' 'UT*' '*aivc-macchina/platform/*' --output-file final.info --ignore-errors empty
          genhtml -o cov_html final.info

      - name: zip files
        run: |
          ls
          tar czvf cov_html.tar.gz cov_html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cov_html.tar.gz
          
      - name: print variable
        run: | 
          echo $TEST_RES
          
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true

